function Corr_Joint_Sp = corr_brachia_bot(in1,in2)
%CORR_BRACHIA_BOT
%    CORR_JOINT_SP = CORR_BRACHIA_BOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    05-Dec-2015 20:05:53

c2 = in2(4,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
l1 = in2(1,:);
m2 = in2(6,:);
th2 = in1(2,:);
t2 = sin(th2);
Corr_Joint_Sp = [-c2.*dth2.*l1.*m2.*t2.*(dth1.*2.0+dth2);c2.*dth1.^2.*l1.*m2.*t2];
