function Grav_Joint_Sp = grav_brachia_bot(in1,in2)
%GRAV_BRACHIA_BOT
%    GRAV_JOINT_SP = GRAV_BRACHIA_BOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    03-Dec-2015 17:55:56

c1 = in2(3,:);
c2 = in2(4,:);
g = in2(9,:);
l1 = in2(1,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = sin(t3);
Grav_Joint_Sp = [g.*m2.*(c2.*t4+l1.*t2)+c1.*g.*m1.*t2;c2.*g.*m2.*t4];
