function r_B = motor_pos(in1,in2)
%MOTOR_POS
%    R_B = MOTOR_POS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    06-Dec-2015 01:36:52

l1 = in2(1,:);
th1 = in1(1,:);
r_B = [l1.*sin(th1);-l1.*cos(th1);0.0];
