function A = A_double_pendulum(in1,in2)
%A_DOUBLE_PENDULUM
%    A = A_DOUBLE_PENDULUM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    05-Oct-2015 13:27:30

I1 = in2(10,:);
I2 = in2(11,:);
I3 = in2(12,:);
c1 = in2(4,:);
c2 = in2(5,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(7,:);
m2 = in2(8,:);
m3 = in2(9,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = c2.^2;
t3 = l1.^2;
t4 = cos(th2);
t5 = m2.*t2;
t6 = m3.*t2;
t7 = l2.^2;
t8 = m3.*t7;
t9 = th2+th3;
t10 = cos(t9);
t11 = cos(th3);
t12 = c2.*l2.*m3.*t11.*2.0;
t13 = c2.*l1.*m3.*t10;
t14 = c2.*l1.*m2.*t4;
t15 = l1.*l2.*m3.*t4;
t16 = t5+t6+t8+t12+t13+t14+t15;
t17 = c2.*l2.*m3.*t11;
t18 = t6+t13+t17;
t19 = t6+t17;
A = reshape([I1+I2+I3+t5+t6+t8+t12+m2.*t3+m3.*t3+c1.^2.*m1+c2.*l1.*m2.*t4.*2.0+c2.*l1.*m3.*t10.*2.0+l1.*l2.*m3.*t4.*2.0,t16,t18,t16,I2+I3+t5+t6+t8+t12,t19,t18,t19,I3+t6],[3, 3]);
