function b = b_double_pendulum(in1,in2,in3)
%B_DOUBLE_PENDULUM
%    B = B_DOUBLE_PENDULUM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    05-Oct-2015 13:27:31

c1 = in3(4,:);
c2 = in3(5,:);
dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
g = in3(13,:);
l1 = in3(1,:);
l2 = in3(2,:);
m1 = in3(7,:);
m2 = in3(8,:);
m3 = in3(9,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
tau3 = in2(3,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = th2+th3;
t3 = sin(t2);
t4 = sin(th2);
t5 = c2.*dth1.*l1.*m3.*t3.*2.0;
t6 = c2.*dth2.*l1.*m3.*t3;
t7 = c2.*dth3.*l1.*m3.*t3;
t8 = sin(th3);
t9 = th1+th2;
t10 = sin(t9);
t11 = sin(th1);
t12 = l1.*t11;
t13 = c2.*dth1.*l2.*m3.*t8.*2.0;
t14 = c2.*dth2.*l2.*m3.*t8.*2.0;
t15 = c2.*dth3.*l2.*m3.*t8;
t16 = c2.*dth1.*l1.*m3.*t3;
t17 = l2.*t10;
t18 = th1+th2+th3;
t19 = sin(t18);
t20 = c2.*t19;
t21 = dth1.^2;
b = [tau1+dth2.*(t5+t6+t7+c2.*dth1.*l1.*m2.*t4.*2.0+c2.*dth2.*l1.*m2.*t4+dth1.*l1.*l2.*m3.*t4.*2.0+dth2.*l1.*l2.*m3.*t4)+dth3.*(t5+t6+t7+t13+t14+t15)-g.*m2.*(t12+c2.*t10)-g.*m3.*(t12+t17+t20)-c1.*g.*m1.*t11;tau2+dth2.*(t16+c2.*dth1.*l1.*m2.*t4+dth1.*l1.*l2.*m3.*t4)+dth3.*(t13+t14+t15+t16)-g.*m3.*(t17+t20)-c2.*g.*m2.*t10-c2.*l1.*m2.*t4.*t21-c2.*l1.*m3.*t3.*t21-l1.*l2.*m3.*t4.*t21-c2.*dth1.*dth2.*l1.*m2.*t4-c2.*dth1.*dth2.*l1.*m3.*t3-c2.*dth1.*dth3.*l1.*m3.*t3-dth1.*dth2.*l1.*l2.*m3.*t4;tau3+dth3.*(t16+c2.*dth1.*l2.*m3.*t8+c2.*dth2.*l2.*m3.*t8)-c2.*g.*m3.*t19-c2.*l1.*m3.*t3.*t21-c2.*l2.*m3.*t8.*t21-c2.*dth2.^2.*l2.*m3.*t8-c2.*dth1.*dth3.*l1.*m3.*t3-c2.*dth1.*dth2.*l2.*m3.*t8.*2.0-c2.*dth1.*dth3.*l2.*m3.*t8-c2.*dth2.*dth3.*l2.*m3.*t8];
