function E = energy_double_pendulum(in1,in2)
%ENERGY_DOUBLE_PENDULUM
%    E = ENERGY_DOUBLE_PENDULUM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    05-Oct-2015 13:27:31

I1 = in2(10,:);
I2 = in2(11,:);
I3 = in2(12,:);
c1 = in2(4,:);
c2 = in2(5,:);
dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
g = in2(13,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(7,:);
m2 = in2(8,:);
m3 = in2(9,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = dth1.^2;
t3 = dth2.^2;
t4 = c2.^2;
t5 = dth3.^2;
t6 = l1.^2;
t7 = l2.^2;
t8 = th1+th2;
t9 = cos(t8);
t10 = cos(th1);
t11 = l1.*t10;
t12 = cos(th3);
t13 = cos(th2);
t14 = th2+th3;
t15 = cos(t14);
E = I1.*t2.*(1.0./2.0)+I2.*t2.*(1.0./2.0)+I2.*t3.*(1.0./2.0)+I3.*t2.*(1.0./2.0)+I3.*t3.*(1.0./2.0)+I3.*t5.*(1.0./2.0)+c1.^2.*m1.*t2.*(1.0./2.0)-g.*m3.*(t11+l2.*t9+c2.*cos(th1+th2+th3))-g.*m2.*(t11+c2.*t9)+m2.*t2.*t4.*(1.0./2.0)+m2.*t3.*t4.*(1.0./2.0)+m3.*t2.*t4.*(1.0./2.0)+m2.*t2.*t6.*(1.0./2.0)+m3.*t3.*t4.*(1.0./2.0)+m3.*t2.*t6.*(1.0./2.0)+m3.*t2.*t7.*(1.0./2.0)+m3.*t4.*t5.*(1.0./2.0)+m3.*t3.*t7.*(1.0./2.0)+dth1.*dth2.*m2.*t4+dth1.*dth2.*m3.*t4+dth1.*dth3.*m3.*t4+dth2.*dth3.*m3.*t4+dth1.*dth2.*m3.*t7-c1.*g.*m1.*t10+c2.*l1.*m2.*t2.*t13+c2.*l2.*m3.*t2.*t12+c2.*l2.*m3.*t3.*t12+c2.*l1.*m3.*t2.*t15+l1.*l2.*m3.*t2.*t13+c2.*dth1.*dth2.*l1.*m2.*t13+c2.*dth1.*dth2.*l2.*m3.*t12.*2.0+c2.*dth1.*dth3.*l2.*m3.*t12+c2.*dth1.*dth2.*l1.*m3.*t15+c2.*dth2.*dth3.*l2.*m3.*t12+c2.*dth1.*dth3.*l1.*m3.*t15+dth1.*dth2.*l1.*l2.*m3.*t13;
