function keypoints = keypoints_brachia_bot(in1,in2)
%KEYPOINTS_BRACHIA_BOT
%    KEYPOINTS = KEYPOINTS_BRACHIA_BOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    05-Oct-2015 15:56:04

l1 = in2(1,:);
l2 = in2(2,:);
l3 = in2(3,:);
l4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
t2 = sin(th1);
t3 = l1.*t2;
t4 = th1+th2;
t5 = sin(t4);
t6 = l2.*t5;
t7 = th1+th2+th3;
t8 = sin(t7);
t9 = l3.*t8;
t10 = cos(th1);
t11 = cos(t4);
t12 = th1+th2+th3+th4;
t13 = cos(t7);
keypoints = reshape([t3,-l1.*t10,t3+t6,-l1.*t10-l2.*t11,t3+t6+t9,-l1.*t10-l2.*t11-l3.*t13,t3+t6+t9+l4.*sin(t12),-l1.*t10-l2.*t11-l3.*t13-l4.*cos(t12)],[2, 4]);
